# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 13:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailRideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('lat_src', models.FloatField()),
                ('lng_src', models.FloatField()),
                ('lat_dest', models.FloatField()),
                ('lng_dest', models.FloatField()),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AvailToOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.AvailRideModel')),
            ],
        ),
        migrations.CreateModel(
            name='DriverUsers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('driverlicense', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_src', models.FloatField()),
                ('lng_src', models.FloatField()),
                ('lat_dest', models.FloatField()),
                ('lng_dest', models.FloatField()),
                ('waypoints', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='JourneyFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('journeyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('lat_src', models.FloatField()),
                ('lng_src', models.FloatField()),
                ('lat_dest', models.FloatField()),
                ('lng_dest', models.FloatField()),
                ('seats', models.IntegerField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.DriverUsers')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('isdriver', models.BooleanField()),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], default=b'm', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleregistration', models.CharField(max_length=20)),
                ('vehiclemodel', models.CharField(max_length=20)),
                ('milage', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journeyfeedback',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journey',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_passsenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availtooffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.OfferRides'),
        ),
        migrations.AddField(
            model_name='availridemodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
