# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 07:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('isdriver', models.BooleanField()),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], default=b'm', max_length=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='driver_users',
            new_name='DriverUsers',
        ),
        migrations.RenameModel(
            old_name='journey_feeback',
            new_name='JourneyFeedback',
        ),
        migrations.RenameModel(
            old_name='vehicle_details',
            new_name='VehicleDetails',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='uid',
        ),
        migrations.AlterField(
            model_name='journeyfeedback',
            name='journeyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.Journey'),
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
