# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twift', '0002_auto_20160627_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_src', models.FloatField()),
                ('lng_src', models.FloatField()),
                ('lat_dest', models.FloatField()),
                ('lng_dest', models.FloatField()),
                ('seats', models.IntegerField()),
                ('datePublished', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.DriverUsers')),
            ],
        ),
        migrations.AlterField(
            model_name='journeyfeedback',
            name='journeyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.Journey'),
        ),
    ]
