# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twift', '0003_auto_20160630_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrides',
            name='destination',
            field=models.CharField(default=datetime.datetime(2016, 6, 30, 13, 15, 29, 73720, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrides',
            name='source',
            field=models.CharField(default=datetime.datetime(2016, 6, 30, 13, 15, 41, 562430, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journeyfeedback',
            name='journeyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.Journey'),
        ),
    ]
