# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 12:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twift', '0004_auto_20160630_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='availRideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('startx', models.FloatField()),
                ('starty', models.FloatField()),
                ('destinationx', models.FloatField()),
                ('destinationy', models.FloatField()),
                ('datePublished', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='journeyfeedback',
            name='journeyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.Journey'),
        ),
    ]
