# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twift', '0006_auto_20160707_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyfeedback',
            name='journeyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twift.Journey'),
        ),
    ]
